version: '3.8'
services:
  app:
    container_name: api
    build: .
    restart: always
    volumes:
      - .:/app
    depends_on:
      - mysql          
    ports: 
      - 8080:8080 

  mysql:
    image: mysql:8.0.31
    container_name: db_mysql
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_USER= "mysql"
      - MYSQL_PASSWORD= "mysql_pass"
      - MYSQL_DATABASE= "avito_user_balance_api"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
